/**
 * Pre-build step: writes public/robots.txt.
 *
 * sitemap.xml and llms.txt are generated by prerender.js instead, because it
 * runs after the build and has the real ROUTES array — see scripts/seo-lib.mjs.
 * This script only needs to exist for the static robots.txt so the dev server
 * and production serve the same file.
 */

import { writeFileSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildRobots } from './seo-lib.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PUBLIC = resolve(__dirname, '..', 'public');

const path = resolve(PUBLIC, 'robots.txt');
const content = buildRobots();
let changed = true;
try {
  changed = readFileSync(path, 'utf-8') !== content;
} catch {
  // new file
}
writeFileSync(path, content);
console.log(`[seo] robots.txt${changed ? '' : ' (unchanged)'}`);
